# .github/workflows/main.yml
name: Build
on:
  push:
    braches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Getting Go Binaries
      uses: actions/setup-go@v2
      with:
          go-version: '1.18'
    - name: Build Application
      run: |
          go get -u && go mod tidy
          go build -o rest-server
    - name: Create Zip
        run: |
          zip -r /tmp/rest-server-${{ github.run_number }}.zip rest-server
    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
          files: /tmp/rest-server-${{ github.run_number }}.zip
          name: "Release ${{ github.run_number }}"
          tag_name: "release.${{ github.run_number }}"